[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "PyYAML",
    "pyserial",
    "ruamel.yaml"
]

[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-cov"
]