---
  serial:
    port: COM5
    baudrate: 57600
  poteaux: # distances en mm
    moteur1:
      poles:
        x: 0
        y: 0
        z: 0
      accroches:
        x: -55
        y: 100
        z: 0
    moteur4:
      poles:
        x: 1180
        y: 0
        z: 0
      accroches:
        x: 55
        y: 100
        z: 0
...
    # test2:
    #   poles:
    #     x: 0
    #     y: 0
    #     z: 0
    #   accroches:
    #     x: -1
    #     y: 1
    #     z: 1
    # test3:
    #   poles:
    #     x: 0
    #     y: 0
    #     z: 0
    #   accroches:
    #     x: -1
    #     y: 1
    #     z: 1
