---
  serial:
    port: COM5
    baudrate: 57600
  poteaux: # distances en mm
    moteur2:
      poles:
        x: 0
        y: 0
        z: 0
      accroches:
        x: 0
        y: 0
        z: 75
    moteur3:
      poles:
        x: 1170
        y: 0
        z: 0
      accroches:
        x: 0
        y: 0
        z: 75
...
    # test2:
    #   poles:
    #     x: 0
    #     y: 0
    #     z: 0
    #   accroches:
    #     x: -1
    #     y: 1
    #     z: 1
    # test3:
    #   poles:
    #     x: 0
    #     y: 0
    #     z: 0
    #   accroches:
    #     x: -1
    #     y: 1
    #     z: 1
