name: Tests Python

on: push
# on:
#   push:
#     paths:
#       - '**.py'

jobs:
  pytest_api:
    name: Tests API Python
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
       
      - name: pytest run
        run: |
          pytest --cov=funibot_api --cov-branch --cov-report=xml:./coverage.xml

      - name: coverage report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: python_api
