name: Tests Python

on:
  push:
    paths:
      - '**.py'
      - '**requirements.txt'
      - '**tests_python.yml'
      - 'setup.cfg'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  pytest_api:
    name: Tests API Python
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
       
      - name: pytest run
        run: |
          pytest --cov=funibot_api --cov-branch --cov-report=xml
          pytest --cov=funibot_api --cov-branch --cov-report=html:./coverage.html

      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          flags: python_api

      - name: coverage upload
        uses: actions/upload-artifact@v2
        with:
          name: coverage_${{ matrix.python-version }}
          path: ./coverage.html
